platform :ios, '16.0'

target 'FoodRecipes' do
  use_frameworks!

  # Pods for FoodRecipes

  pod 'FRCommon', :path => 'DevPods/FRCommon'
  pod 'FRCore', :path => 'DevPods/FRCore'
  pod 'FRAPILayer', :path => 'DevPods/FRAPILayer'

end
