platform :ios, '16.0'

target 'FoodRecipes' do
  use_frameworks!

  # Pods for FoodRecipes

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'FirebaseFirestore'
  pod 'FirebaseDatabase'
  pod 'FirebaseStorage'

  pod 'SVProgressHUD'
  pod 'NotificationBannerSwift'

  pod 'FRCommon', :path => 'DevPods/FRCommon'
  pod 'FRCore', :path => 'DevPods/FRCore'
  pod 'FRAPILayer', :path => 'DevPods/FRAPILayer'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
  #        config.build_settings['DEVELOPMENT_TEAM'] = 'FJ98W26Z2V'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
          if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
            target.build_configurations.each do |config|
                config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            end
          end
          if config.name.include?("Debug") || config.name.include?("SIT") || config.name.include?("UAT")
  #          config.build_settings['DEVELOPMENT_TEAM'] = '8N4XNP89QN'
            config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
            config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
          end
        end
      end
    end

end
